--=============================--
-- 由 Telegram@AiWo6 & @clunsdy 汉化
--=============================--

-- 翻译表
local Translations = {
    ["Abysall Hub"] = "Abysall Hub (🇨🇳)",
    ["Toggle"] = "切换",
    ["Lock"] = "锁定",
    ["Locked"] = "上锁",
    ["Keybinds"] = "按键绑定",
    ["Unlock"] = "解锁",
    ["General"] = "一般",
    ["Saves"] = "保存",
    ["Exploits"] = "漏洞",
    ["Visuals"] = "视觉",
    ["Floor"] = "楼层",
    ["Miscellaneous"] = "杂项",
    ["Configuration"] = "配置",
    ["Information"] = "关于",
    ["Character"] = "人物",
    ["Player"] = "玩家",
    ["Misc"] = "音乐",
    ["Creation"] = "创建",
    ["Manager"] = "管理",
    ["Aimbot"] = "自瞄",
    ["Prompt"] = "提示",
    ["Automation"] = "自动",
    ["World"] = "世界",
    ["Prompt"] = "提示",
    ["Disablers"] = "禁用",
    ["Beta Features"] = "Beta 版功能",
    ["Removals"] = "移除",
    ["Bypasses"] = "绕过",
    ["Selection"] = "选择",
    ["Camera"] = "相机",
    ["Effects"] = "效果",
    ["Notifications"] = "通知",
    ["Bypass"] = "绕过",
    ["Audio Tweaks"] = "音效调整",
    ["Other"] = "其他",
    ["Themes"] = "主题",
    ["Settings"] = "设置",
    ["Supported Games"] = "支持的游戏",
    ["Extra"] = "额外",
    ["Socials"] = "群组",
    ["Contributors"] = "贡献者",

    ["Walkspeed"] = "步行速度",
    ["Enable"] = "启用",
    ["Speed Boost"] = "速度调整",
    ["Ladder Speed"] = "爬梯速度",
    ["Jump Power"] = "跳跃高度",
    ["Fast Closet Exit"] = "快速退出柜子",
    ["No Acceleration"] = "无加速",
    ["Noclip"] = "穿墙",
    ["Jumping"] = "跳跃",
    ["Flight"] = "飞行",
    ["Flight Speed"] = "飞行速度",
    ["Instant Prompts"] = "立即交互",
    ["Prompt Clip"] = "隔墙交互",
    ["Distance Multiplier"] = "交互距离",
    ["Cycle Achievements"] = "循环成就",
    ["Cycle Delay"] = "周期延迟",
    ["Auto Join Elevator"] = "自动加入电梯",
    ["Redeem all Codes"] = "兑换所有代码",
    ["Rejoin Server"] = "重新加入服务器",
    ["Auto Interact"] = "自动交互",
    ["Ignore List"] = "忽略列表",
    ["Jeff Items"] = "杰夫商店",
    ["Minecarts"] = "矿车",
    ["Doors"] = "门",
    ["Door"] = "门",
    ["Paintings"] = "画",
    ["Locked Items"] = "上锁物品",
    ["Dropped Items"] = "掉落物品",
    ["Loot Items"] = "可互动箱子",
    ["Ladders"] = "梯子",
    ["Ladder"] = "梯子",
    ["Gold"] = "金子",
    ["Interact Delay"] = "交互延迟",
    ["Auto Closet"] = "自动躲藏",
    ["Spectate Mode"] = "观察模式",
    ["Player to Entity"] = "玩家看实体",
    ["Entity to Player"] = "实体看玩家",
    ["Spectate Entity"] = "观察实体",
    ["Door Reach"] = "开门范围",
    ["Transparent Closets"] = "透明柜子",
    ["Transparent"] = "透明度",
    ["Max Players"] = "最大玩家数量",
    ["Modifiers"] = "修饰符",
    ["Destination"] = "目的地",
    ["Friends Only"] = "仅限好友",
    ["Create Elevator"] = "创建电梯",
    ["Import from Game UI"] = "从游戏 UI 导入",
    ["Disable"] = "禁用",
    ["Obstrctions"] = "障碍物",
    ["Damage"] = "伤害",
    ["Elevator name"] = "电梯名称",
    ["Create elevator"] = "创建电梯",
    ["Saved elevators"] = "已保存的电梯",
    ["Load elevator"] = "载重电梯",
    ["Overwrite elevator"] = "覆盖电梯",
    ["Delete elevator"] = "删除电梯",
    ["Target Part"] = "瞄准部位",
    ["HumanoidRootPart"] = "身体",
    ["Head"] = "头部",
    ["Distance Type"] = "距离类型",
    ["Checks"] = "检测",
    ["Whitelist"] = "白名单",
    ["Alive"] = "存活",
    ["Forcefield"] = "护盾",
    ["Team"] = "队伍",
    ["Wall"] = "墙壁",
    ["Circle"] = "圆圈",
    ["Circle Size"] = "圆圈大小",
    ["Circle Thickness"] = "圆圈厚度",
    ["Position Spoof"] = "遁地术",
    ["Spoof Position"] = "遁地术",
    ["Godmode"] = "无敌",
    ["Speed Bypass"] = "速度绕过",
    ["Crouch Spoof"] = "防 Figure 听觉",
    ["Anticheat Manipulation"] = "反作弊操作",
    ["Manipulation Method"] = "操作方法",
    ["Pivot"] = "鬼步法",
    ["Velocity"] = "直穿法",
    ["Infinite"] = "无限",
    ["Item List"] = "物品列表",
    ["Lockpicks"] = "撬锁器",
    ["Skeleton Key"] = "骷髅钥匙",
    ["Shears"] = "剪刀",
    ["Toolbox"] = "工具箱",
    ["Toolshed"] = "工具棚",
    ["Multitool"] = "多功能工具",
    ["Item Silent Aim"] = "道具自瞄",
    ["Silent Aim Range"] = "自瞄范围",
    ["Show Range"] = "显示范围",
    ["Objectives"] = "必要品",
    ["Hiding Places"] = "藏身点",
    ["Sitting"] = "坐下",
    ["Touching"] = "触碰",
    ["Selected"] = "选择",
    ["Goto"] = "传送",
    ["Fling"] = "甩飞",
    ["Players"] = "玩家",
    ["Chests"] = "箱子",
    ["Items"] = "物品",
    ["Stardust"] = "星尘",
    ["Fake Doors"] = "假门",
    ["Entities"] = "实体",
    ["Entity"] = "实体",
    ["Rainbow"] = "彩虹",
    ["Use Team Color"] = "使用队伍颜色",
    ["Transparency"] = "透明度",
    ["Fill Transparency"] = "填充透明度",
    ["Outline Transparency"] = "轮廓透明度",
    ["Text Transparency"] = "文本透明度",
    ["Fade Time"] = "渐隐时间",
    ["Text Outline Transparency"] = "文本轮廓透明度",
    ["Text Size"] = "文本大小",
    ["Text Font"] = "文本字体",
    ["Custom Outline Color"] = "自定义轮廓颜色",
    ["Show Distance"] = "显示距离",
    ["Enable Tracers"] = "启用追踪线",
    ["Tracer Thickness"] = "追踪线宽度",
    ["Tracer Origin"] = "追踪线起点",
    ["Bottom"] = "底部",
    ["Top"] = "顶部",
    ["Center"] = "中心",
    ["Mouse"] = "鼠标",
    ["Enable Arrows"] = "启用箭头",
    ["Arrow Radius"] = "箭头半径",
    ["Ambience"] = "环境光",
    ["Field Of View"] = "视野",
    ["Field of View"] = "视野",
    ["Third Person"] = "第三人称",
    ["Offset"] = "偏移",
    ["No Death Jumpscare"] = "无死亡跳杀",
    ["No Hiding Effects"] = "无隐藏效果",
    ["No Fog Effects"] = "无雾",
    ["No Seek Effects"] = "无 Seek 效果",
    ["No Camera Shake"] = "无相机震动",
    ["No Camera Bobbing"] = "无相机晃动",
    ["No Timothy Jumpscare"] = "无 Timothy 跳杀",
    ["No Glitch Jumpscare"] = "无 Glitch 跳杀",
    ["No Void Jumpscare"] = "无 Void 跳杀",
    ["Viewmodel Offset"] = "视角模型偏移",
    ["Entity List"] = "实体列表",
    ["Notify Entities"] = "通知实体",
    ["Chat Notify"] = "聊天通知",
    ["Notify Message"] = "通知消息",
    ["Enter Message Here"] = "请输入文本",
    ["Play Sound"] = "播放声音",
    ["Sound Volume"] = "音量",
    ["Notification Style"] = "通知样式",
    ["Send Notification Test"] = "发送通知测试",
    ["Auto Breaker Puzzle"] = "自动配电器",
    ["Auto Heartbeat Minigame"] = "自动心跳游戏",
    ["Auto Anchor Code"] = "自动锚点代码",
    ["Auto Solve Anchors"] = "自动解决锚点",
    ["Auto Eat Candies"] = "自动吃糖果",
    ["Candy Ignore List"] = "糖果忽略列表",
    ["Auto Library Code"] = "自动提示挂锁密码",
    ["Auto Unlock Padlock"] = "自动解锁挂锁",
    ["Unlock Distance"] = "解锁距离",
    ["Auto Minecart"] = "自动矿车",
    ["Crouch Distance"] = "蹲下距离",
    ["Turn Distance"] = "转向距离",
    ["Delete"] = "删除",
    ["Anticheat Bypass"] = "反作弊绕过",
    ["Viusals"] = "视觉",
    ["Notify Oxygen Level"] = "显示氧气时间",
    ["Notify Haste Time"] = "显示 Haste 时间",
    ["Notify Hide Time"] = "显示 Hide 时间",
    ["Show Seek Path"] = "显示 Seek 路径",
    ["Show Eyestalk Path"] = "显示 Eyestalk 路径",
    ["Disable Firedamp Effects"] = "禁用沼气效果",
    ["Remove Footstep Sounds"] = "禁用脚步声",
    ["Remove Jammin Music"] = "禁用 Jammin 音乐",
    ["Remove Interacting Sounds"] = "禁用交互声音",
    ["Remove Damage Sounds"] = "禁用受伤音效",
    ["Disable AFK Kick"] = "禁用挂机踢出",
    ["Auto Play Rooms"] = "自动 Rooms",
    ["Show Path"] = "显示路径",
    ["Predict"] = "预测",
    ["Predict"] = "去除",
    ["Basement"] = "地下室",
    ["Painting"] = "画房",
    ["Skeleton"] = "骷髅",
    ["Auto Play"] = "自动游戏",
    ["Teleport Delay"] = "传送延迟",
    ["Trigger"] = "触发",
    ["Ignore"] = "忽略",
    ["Avoid"] = "避免",
    ["Remove"] = "移除",
    ["Revive"] = "复活",
    ["Revives"] = "复活",
    ["Kill Character"] = "自杀",
    ["Reset"] = "重置",
    ["Play Again"] = "重开",
    ["Return to Lobby"] = "返回",
    ["Server Hop"] = "切换服务器",
    ["Instant Leave"] = "退出服务器",
    ["Are you sure"] = "你确定吗",
    ["Background color"] = "背景颜色",
    ["Main color"] = "主色调",
    ["Accent color"] = "强调色",
    ["Outline color"] = "轮廓颜色",
    ["Font color"] = "字体颜色",
    ["Font Face"] = "字体",
    ["Theme list"] = "主题列表",
    ["Set as default"] = "设为默认",
    ["Reset default"] = "重置默认值",
    ["Custom theme name"] = "自定义主题名称",
    ["Create theme"] = "创建主题",
    ["Custom themes"] = "自定义主题",
    ["Load theme"] = "加载主题",
    ["Overwrite theme"] = "覆盖主题",
    ["Delete theme"] = "删除主题",
    ["Refresh list"] = "刷新列表",
    ["Show Keybinds"] = "显示按键绑定",
    ["Custom Cursor"] = "自定义光标",
    ["Toggle Keybind"] = "切换按键绑定",
    ["Scale"] = "比例",
    ["Copy Discord Invite"] = "复制 Discord 邀请",
    ["Copy Discord Link"] = "复制 Discord 链接",
    ["Unload"] = "卸下",
    ["Reload"] = "重新加载",
    ["Config name"] = "配置名称",
    ["Create config"] = "创建配置",
    ["Config list"] = "配置列表",
    ["Load config"] = "加载配置",
    ["Overwrite config"] = "覆盖配置",
    ["Delete config"] = "删除配置",
    ["Set as autoload"] = "自动加载",
    ["Reset autoload"] = "重置自动加载",
    ["Current autoload config:"] = "当前自动加载配置:",

    ["Door"] = "门",
    ["Chest"] = "箱子",
    ["Vine"] = "藤蔓",
    ["Lighter"] = "打火机",
    ["Flashlight"] = "手电筒",
    ["Vitamins"] = "维他命",
    ["Crucifix"] = "十字架",
    ["Skeleton Key"] = "骷髅钥匙",
    ["Gummy Flashlight"] = "手摇手电筒",
    ["Candle"] = "蜡烛",
    ["Moonlight Candle"] = "月光蜡烛",
    ["Star Vial"] = "星光小瓶",
    ["Star Bottle"] = "星光瓶",
    ["Star Jug"] = "星光桶",
    ["Laser Pointer"] = "激光笔",
    ["Battery Pack"] = "电池包",
    ["Bandage Pack"] = "绷带包",
    ["Shears"] = "剪刀",
    ["Toolshed"] = "工具棚",
    ["Glowstick"] = "荧光棒",
    ["Spotlight"] = "大灯",
    ["Straplight"] = "绑带灯",
    ["Dumpster"] = "垃圾桶",
    ["Alarm Clock"] = "闹钟",
    ["Smoohie"] = "啤酒",
    ["Moonlight Smoohie"] = "月光啤酒",
    ["Gween Soda"] = "绿色汽水",
    ["Bread"] = "面包",
    ["Cheese"] = "奶酪",
    ["Donut"] = "甜甜圈",
    ["Aloe"] = "芦荟",
    ["Compass"] = "罗盘",
    ["Lantern"] = "灯笼",
    ["Lotus Petal"] = "莲花",
    ["Iron Key"] = "铁钥匙",
    ["Multi Tool"] = "多功能工具",
    ["Tip Jar"] = "小费罐",
    ["Rift Jar"] = "裂隙罐",
    ["Puzzle Painting"] = "拼图画",
    ["Library Paper"] = "密码纸",
    ["Breaker"] = "断路器",
    ["Generator Fuse"] = "保险丝",
    ["Lotus Petal"] = "花瓣",
    ["Battery"] = "电池",
    ["Bandage"] = "绷带",
    ["Glitch Fragment"] = "故障碎片",
    ["Lever"] = "拉杆",
    ["Time Lever"] = "计时器杆",
    ["Star Dust"] = "星尘",
    ["Generator"] = "发电机",
    ["Ladder"] = "梯子",
    ["Door Key"] = "门钥匙",
    ["Anchor"] = "锚点",
    ["Book"] = "书",
    ["Electrical Key"] = "配电室钥匙",
    ["Gate"] = "大门",
    ["Button"] = "按钮",
    ["Water Pump"] = "水阀",
    ["Pipe"] = "水管",
    ["Bed"] = "床",
    ["Double Bed"] = "双人床",
    ["Closet"] = "橱柜",
    ["Locker"] = "铁柜",
    ["Mouse Hole"] = "老鼠洞",
    ["Item Locker"] = "物品柜",
    ["Herb of Viridis"] = "药草",
    ["Gold"] = "黄金",
    ["Stardust Pile"] = "星尘",
    ["Vacuum"] = "虚空",
    ["THE EVIL KEY"] = "邪恶的钥匙",
    ["Hole"] = "洞",
    ["Snare"] = "陷阱",
    ["Ladder"] = "梯子",
    ["Toolbox"] = "工具箱",
    ["Fridge Locker"] = "冰箱柜",
    ["Vine Lever"] = "藤蔓断头台",
    ["Vial of Starlight"] = "星光小瓶",
    ["Bottle of Starlight"] = "星光瓶",
    ["Barrel of Starlight"] = "星光桶",
    ["Win Shield"] = "胜利护盾",
    ["Big Shield Potion"] = "大护盾药水",
    ["Small Shield Potion"] = "小护盾药水",
    ["Holy Hand Grenade"] = "圣手雷",

    ["has spawned"] = "已生成",
    ["has spawned. Hide!"] = "已生成. 隐藏!",
    ["Find a hiding spot quickly"] = "快找到藏身点",
    ["Avoid looking at it"] = "避免看它",
    ["will spawn in the next room"] = "将在下一门生成",
    ["Turn off lights for the next few rooms"] = "接下来几间房间要关灯",
    ["Successfully bypassed the Anticheat"] = "成功绕过反作弊",
    ["It will only last until the next cutscene"] = "它只会持续到下个过场动画",
    ["The anticheat bypass has been broken"] = "反作弊绕过已失效",
    ["Get on a ladder to fix it"] = "爬上梯子修复",
    ["Your movement is now fully automated"] = "您的行动现已完全自动化",
    ["Avoid walking on the grass"] = "避免在草地上行走",
    ["Position Spoof doesn't work on A-120"] = "遁地术在 A-120 上不起作用"
}

-- 按长度排序，保证长词优先
local keys = {}
for k in pairs(Translations) do
    table.insert(keys, k)
end
table.sort(
    keys,
    function(a, b)
        return #a > #b
    end
)

-- 替换函数（纯文本，不走正则）
local function safeReplace(text, old, new)
    local result = ""
    local start = 1
    while true do
        local i, j = string.find(text, old, start, true) -- plain = true
        if not i then
            result = result .. string.sub(text, start)
            break
        end
        result = result .. string.sub(text, start, i - 1) .. new
        start = j + 1
    end
    return result
end

-- 翻译函数
local function translateText(text)
    if not text or type(text) ~= "string" then
        return text
    end
    for _, k in ipairs(keys) do
        text = safeReplace(text, k, Translations[k])
    end
    return text
end

-- Hook UI 赋值
local oldNewIndex
oldNewIndex =
    hookmetamethod(
    game,
    "__newindex",
    function(self, key, value)
        if key == "Text" and type(value) == "string" then
            value = translateText(value)
        end
        return oldNewIndex(self, key, value)
    end
)

-- 最后加载远程脚本
loadstring(game:HttpGet("https://raw.githubusercontent.com/bocaj111004/AbysallHub/refs/heads/main/Loader.lua"))()